# -*- coding: utf-8 -*-
"""Sistem Pakar Hama

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggMyUPSWKe9gXw3JcQqPhtwEiZlMPHeM
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class HamaTanaman(KnowledgeEngine):
    # Aturan 1: Kutu Daun (Aphids)
    @Rule(Fact(daun_menguning=True) & Fact(bercak_hitam=True))
    def kutu_daun(self):
        print("Hama yang teridentifikasi: Kutu Daun (Aphids)")
        print("Solusi: Gunakan insektisida sistemik atau semprot dengan air sabun")

    # Aturan 2: Ulat Grayak (Armyworm)
    @Rule(Fact(daun_berlubang=True) & Fact(tanaman_layu=True))
    def ulat_grayak(self):
        print("Hama yang teridentifikasi: Ulat Grayak (Armyworm)")
        print("Solusi: Gunakan pestisida biologis seperti Bacillus thuringiensis")

    # Aturan 3: Tungau (Spider Mite)
    @Rule(Fact(daun_menguning=True) & Fact(tanaman_layu=True))
    def tungau(self):
        print("Hama yang teridentifikasi: Tungau (Spider Mite)")
        print("Solusi: Tingkatkan kelembapan dan gunakan mitisida")

    # Aturan 4: Kumbang (Beetle)
    @Rule(Fact(bercak_hitam=True) & Fact(daun_berlubang=True))
    def kumbang(self):
        print("Hama yang teridentifikasi: Kumbang (Beetle)")
        print("Solusi: Gunakan perangkap feromon atau insektisida kontak")

    # Aturan untuk kasus tidak dikenali
    @Rule(
        NOT(Fact(daun_menguning=True) & Fact(bercak_hitam=True)),
        NOT(Fact(daun_berlubang=True) & Fact(tanaman_layu=True)),
        NOT(Fact(daun_menguning=True) & Fact(tanaman_layu=True)),
        NOT(Fact(bercak_hitam=True) & Fact(daun_berlubang=True))
    )
    def hama_tidak_dikenali(self):
        print("Hama tidak dapat diidentifikasi berdasarkan gejala yang diberikan")
        print("Silakan konsultasikan dengan ahli pertanian setempat")

def get_input():
    """Fungsi untuk mendapatkan input gejala dari pengguna"""
    def tanya_gejala(pertanyaan):
        return input(pertanyaan + " (ya/tidak): ").strip().lower() == "ya"

    print("\nMasukkan gejala yang diamati pada tanaman:")
    return {
        "daun_menguning": tanya_gejala("Apakah daun menguning?"),
        "bercak_hitam": tanya_gejala("Apakah terdapat bercak hitam pada daun?"),
        "daun_berlubang": tanya_gejala("Apakah daun berlubang?"),
        "tanaman_layu": tanya_gejala("Apakah tanaman layu?")
    }

if __name__ == "__main__":
    print("=== Sistem Pakar Identifikasi Hama Tanaman ===")
    print("Silakan jawab pertanyaan berikut dengan 'ya' atau 'tidak'\n")

    gejala = get_input()
    engine = HamaTanaman()
    engine.reset()

    # Deklarasikan fakta-fakta berdasarkan input pengguna
    for gejala_nama, ada in gejala.items():
        engine.declare(Fact(**{gejala_nama: ada}))

    # Jalankan sistem pakar
    engine.run()